### ISSUE TITLE
Странности с интерфейсом

### ISSUE THREAD

**Issue by annikoff** [smalew/reminder#3]
Теперь вот такая поблема
![reminder v 0 9_001](https://cloud.githubusercontent.com/assets/3622880/13076112/20fb44fe-d4c1-11e5-8555-e917ee92cce9.png)

**Comment by dkoropenko** [comment]
Прога не видит папки resource 
переписал gitignore
Должно заработать.

Обновил еще и GUI немного.

**Comment by dkoropenko** [comment]
Собрал проект.
Лежит в alfa\out\artifacts\alfa_jar

**Comment by dkoropenko** [comment]
Да, действительно под linux имеются проблемы с путями до БД и ресурсов.
Поправлю. Об изменениях напишу тут.

**Comment by dkoropenko** [comment]
Решил проблему.
Запускай программу через Alfa.sh
